### ISSUE TITLE
Should the UI try to 'teach' the user about the underlying data model? 

### ISSUE THREAD

**Issue by simontegg** [open-app/holodex#46]
If so, why?

**Comment by bhaugen** [comment]
@simontegg - this is a really interesting issue. I think the answer depends on who the user is and what they are trying to do.

We don't have enough data to provide any impartial arbitration of design, but we did find in some cases where we hid the data model to make the activity simpler in one case (hiding the process for people logging some work), it caused problems for the same users in other cases where they needed to understand how other kinds of inputs and outputs fit into a process, because they did not understand the model of a process.

You could conjecture that the model was too complicated, but we've now seen several other groups evolving the same model for the same situation, so we suspect it is necessary complexity in the model. And some people never needed to understand the model of a process, all they needed to do was log some work or some other input (for example, they used the 3D printer for an hour).

And the people who worked on configuring the system, or designing recipes, or planning, clearly needed to understand the model pretty well.

In the holodex case, will such users exist (that need to understand the model)? Or can the model create itself from model-blind user interactions?

So I can think of more than one question here:
- Should the UI teach the user about the model?
- Why?
- I think if the answer to the first question is "maybe", then "why" becomes "in what cases?", or "when?"
- How? I've seen examples where the UI did teach the user about the model interactively. The best example I can think of is dead now, unfortunately. Here are some examples that are still alive:
  https://online-go.com/puzzles

**Comment by simontegg** [comment]
Thanks @bhaugen. That's a better reframing. 
Funny you mention Go. @ahdinosaur was just talking about making a Go plugin for secure-scuttlebutt (which already has cryptographically-secure, decentralised tic-tac-toe :)

**Comment by ahdinosaur** [comment]
my feeling is we want our data models to be as simple as possible to support the target domain, with the intention that the interfaces based on these models are also as simple as possible to support the target workflow. with that in mind, i'd rather we base our interfaces on our models, so that if our interfaces are too complex it probably means our models are too complex. that being said, even interfaces based on simple models can appear complicated to the lay user, but i'd rather then that we focus on providing better in-app education to our users than dumbing down the app.

**Comment by simontegg** [comment]
See my [comment](https://github.com/open-app/holodex/issues/45#issuecomment-93874180) in the related thread. I don't consider the use of what I frame as 'System 1 models' to be 'dumbing down'. This is just the perennial tension between two valid modes of thinking.

**Comment by ahdinosaur** [comment]
hmm. in the related thread about how to interface with 'stewardship', if it's only possible to view 'is stewarded by' and 'is steward of', this is less than you can view with a more general control that let's you view each role as being shown or not shown, with a variety of arrow types between the roles.

i think i see what you're saying in that it's not explicitly 'dumber', so a good question is whether the more advanced functionality we'd lose by reducing to only support easier cases is useful at all.

my intuition tells me we want to support raw functionality over only supporting the reduced cases, as i want to build systems that people can use in ways i never imagined rather than be limited to the extent of what i thought was possible.

**Comment by simontegg** [comment]
I don't understand this bit

> this is less than you can view with a more general control that let's you view each role as being shown or not shown, with a variety of arrow types between the roles.

where everything in square brackets is a tag:
[steward] [steward of] 
[stewardee] [stewarded by]
each of which toggles visual elements off and on
then how is this less functionality?

**Comment by ahdinosaur** [comment]
ah okay, sorry i didn't realize the steward and stewardee tags would also be there. hmm, i think i could get on board with this.

**Comment by simontegg** [comment]
Relevant: http://hintjens.com/blog:19

> We apply one measure of quality to patches, namely "can this be done any simpler while still solving the stated problem?" We can measure complexity in terms of concepts and models that the user has to learn or guess in order to use the patch. The fewer, the better. A perfect patch solves a problem with zero learning required by the user.
