### ISSUE TITLE
many group logos cut off in the circle format

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#53]
problem: many group logos cut off in the circle format

**Comment by simontegg** [comment]
Mockups/screenshots needed

**Comment by simontegg** [comment]
This can be solved in other ways (e.g. by requiring a circle friendly logo for group avatars)

**Comment by ahdinosaur** [comment]
behold, the beautiful logo for our group that we paid a designer to create!

![cw-clip](https://cloud.githubusercontent.com/assets/719605/8107898/f54aa596-10a0-11e5-8e50-b61c835569d4.png)

darn, we really want:

![cw-clip1](https://cloud.githubusercontent.com/assets/719605/8107990/b2e52176-10a1-11e5-83bf-b9e22c7c64fc.png)

but yeah, i think it's unreasonable to assume groups want a circle as their avatar, when it's more likely they already went through the effort to make a logo that fits within a square or rectangle. what are the reasons for wanting only circles as avatars? i could see wanting a polygon that packs tightly (tiling hexagons as in phoenix comes to mind), but circles aren't the best for that either. i could see making an option within the data to solve this problem, but that's more work.

**Comment by simontegg** [comment]
Since this only affects 1 logo, a simpler fix is resizing the logo, and putting more grey around it so that it fits within a circle. Plenty of apps enforce logo and avatar dimensions. The question is one of design.

In terms of process, I'm not quite sure how to handle this in regards to C4.   I'm not entirely sure of a good process, but since this simple patch has a huge impact on the look and feel of the app I think a fuller design process is appropriate.

For that reason, when I say it needs mockups or screenshots I mean mockups of the suggested design in the context of an example page (with real data). Which is then approved by a person or people (preferably ones who are not developers and/or experienced in design).

**Comment by ahdinosaur** [comment]
from a screenshot of my [patch](https://github.com/holodex/app/pull/96)

![cw-clip2](https://cloud.githubusercontent.com/assets/719605/8120408/f614e322-10f2-11e5-9b81-efd8e21eca7d.png)

with [rectangular backgrounds](https://github.com/holodex/app/pull/96#discussion_r32187827)

![cw-clip5](https://cloud.githubusercontent.com/assets/719605/8120513/093255d8-10f4-11e5-9470-ab1785434f1a.png)

![cw-clip4](https://cloud.githubusercontent.com/assets/719605/8120407/f614656e-10f2-11e5-95cb-2dd50ab10e10.png)

from C4,

> - A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.
> - Maintainers SHALL NOT make value judgments on correct patches.
> - Any Contributor who has value judgments on a correct patch SHOULD express these via their own patches.

...

@nanz was the one who brought up the problem of the Craftworks logo and asked if group logos could be rectangular.

**Comment by simontegg** [comment]
That's good. But Simplicity Oriented Design also emphasises how UI patch complexity can be evaluated on the number of new concepts the patch introduces. In this case, the patch introduces 1-2 new concepts: 
- (general) Avatar shapes correspond to agent types
- Squares == groups
- circles == people

and a new bug: arrowheads are sometimes obscured. 

In terms of process, my thoughts are still half formed but something like the following for UI issues:
1. the issue should be phrased as a problem (group logos are sometimes partially obscured) rather than as a solution ("group icons should be square")
2. Before code is written the design patch submitter submits a design
3. The patch submitter can begin writing code if they want (lazy consensus)
4. If there is objection, the objection is only an evaluation of the number of new concepts in comparison to other solutions that solve the problem with less new concepts
5. ???

In this case, because the design introduces new concepts and a new bug I think it should pass a higher acceptance criteria than patches that do not. Perhaps show the screenshots to nanz and/or a few others, and discuss in regards to my alternative patch (below)?  

My alternative patch is going to be a resizing of the Craftworks logo (0 new concepts, 0 new bugs, +-1 loc)

**Comment by ahdinosaur** [comment]
@simontegg reason for closing?

**Comment by simontegg** [comment]
No good reason. Whoops.
