### ISSUE TITLE
Problem: It is hard to read legend items off the side.

### ISSUE THREAD

**Issue by simontegg** [open-app/holodex#78]

**Comment by simontegg** [comment]
Proposed Solution:

Split the 'query' elements (the tags that control which agents are present) away from the 'legend' / 'annotation' elements. Placing the latter at the center bottom (as in google maps) on demand.

Additionally this design..
- Give the user more control over the visual elements logic through the use of toggles attached to the legend items

On demand means:
- a link-query: "[agentype] that [verb] [target]" brings in its specific link toggle legend item
- a role-query: "a [role] in [context]" brings in its role/halo toggle item
- if only one role-query is present no legend toggle elements are shown.

I've started using Atomic for design and to show the interaction logic. The first run is here: https://beta.atomic.io/d/2oKCUOzyYEow# . Please check out and give feedback on both the visual aesthetics and the interaction/display logic

**Comment by ahdinosaur** [comment]
@simontegg awesome work! :+1: 

on a somewhat related but tangential note, i've been starting to think that roles are really relationships with the context agent. instead of 'Alice is a collaborator in Acme', it might be better as 'Alice collaborates with Acme'. how this relates is that it might be worth ditching roles altogether and just focusing on relationships, but ymmv.

**Comment by simontegg** [comment]
Note: It seems that if the relationship is with the context group the halos are useful but arrows might be superfluous (they point to or away from the group). In this case showing these relationships with halos is more useful.
