### ISSUE TITLE
problem: we don't have a data api

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/holodex#80]
#72 is a potentially massive task, so i'm going to be breaking it up into as small objectives as possible in order to minimize the time i spend between pull requests.

first objective of #72: make a sweet interface to the api that integrates well with [NuclearJS](https://github.com/optimizely/nuclear-js). luckily, [they already have an example of such an interface](https://github.com/optimizely/nuclear-js/blob/master/examples/rest-api/), so my plan is to copy that into an isomorphic flux api interface using [feathers](https://github.com/feathersjs/feathers) + [feathers-client](https://github.com/feathersjs/feathers-client) as the service interface and [primus](https://github.com/primus/primus) + [ws](https://github.com/websockets/ws) as the transport interface.

~~TODO~~ ([new TODO](https://github.com/open-app/holodex/issues/80#issuecomment-138290894))
- ~~[x] .create `feathers-primus` module to isomorphically use primus with feathers~~
  - ~~[x] test~~
- ~~[ ] create `nuclear-service` module based on [examples/rest-api/src/modules/user/model](https://github.com/optimizely/nuclear-js/blob/master/examples/rest-api/src/modules/user/model.js)~~
  - ~~[ ] test~~
- ~~[ ] create `nuclear-api` module based on [examples/rest-api/src/modules/rest-api](https://github.com/optimizely/nuclear-js/tree/master/examples/rest-api/src/modules/rest-api)~~
  - ~~[ ] test~~

**Comment by bhaugen** [comment]
When you-all settle down into one technical stack, we will follow you.

**Comment by ahdinosaur** [comment]
@bhaugen great. :smile: assembling and maintaining a modular, high-quality, stable technical stack for use in a variety of apps is the path i want to be on, given my 'jack-of-all-stacks' interest and skill. especially relevant now that i'm going to be contracting and want to be in a position to effectively craft apps on-demand using my preferred tooling.

**Comment by ahdinosaur** [comment]
for reference, @bhaugen and i had a parallel discussion on the 'stack' following https://github.com/holodex/app/issues/60#issuecomment-131640164.

**Comment by ahdinosaur** [comment]
i've changed my mind on this one: [`fsdown`](https://github.com/holodex/fsdown/tree/fsdown), [`level-model`](https://github.com/sethvincent/level-model), [`multilevel`](https://www.npmjs.com/package/multilevel), and [`websocket-stream`](https://github.com/maxogden/websocket-stream) seems much simpler.

TODO:
- [ ] create and test [`fsdown`](https://github.com/holodex/fsdown/tree/fsdown) module to mutate the filesystem compatibly with [`abstract-leveldown`](https://github.com/Level/abstract-leveldown/)
- [ ] create and test isomorphic `redux-api`
  - [ ] use [`level-model`](https://github.com/sethvincent/level-model) to generate server interfaces based on every vocab
  - [ ] use [`multilevel`](https://www.npmjs.com/package/multilevel) and [`websocket-stream`](https://github.com/maxogden/websocket-stream) to stream the interfaces to the client

---

dream notes:
- [ ] use [`levi`](https://github.com/cshum/levi) to stream full-text search interfaces to the client

**Comment by ahdinosaur** [comment]
the other option is the use [scuttlebot's api](https://github.com/ssbc/scuttlebot/blob/cli/api.md) as our data api [[#233](https://github.com/ssbc/scuttlebot/issues/233)]. @pfraze has been very responsive in writing much-needed documentation to make this possible, ta. :cake: 

could start with read / write streams to / from a csv database over [`muxrpc`](https://github.com/ssbc/muxrpc), then make a [vocab](https://github.com/openvocab/agent)-based rpc interface with schema validation similar to [`level-model`](https://github.com/sethvincent/level-model). easy to reflect to client with [`pull-ws-server`](https://www.npmjs.com/package/pull-ws-server). as a note, this means moving to [pull-streams](https://www.npmjs.com/package/pull-stream) ([tutorial](https://github.com/dominictarr/pull-stream-examples))

this approach leans more towards experimental mad science, but i do think it would be advantageous for Holodex to start leveraging the work of @dominictarr and @pfraze with ssb as soon as possible, as a way of validating that the ssb is a valuable platform for apps. full adoption of The SSB Way is a mile away, so we'd be taking it on a single step at a time.

**Comment by bhaugen** [comment]
@ahdinosaur - who would use this scuttlebot api? Would it be a requirement (dependency) for other apps that want to feed data to holodex? Or is this just for connecting enspiral apps to holodex? Or what?

**Comment by ahdinosaur** [comment]
Holodex would use the scuttlebot api behind the scenes to power our own api that we expose. it wouldn't be a requirement for other apps that want to feed data to Holodex, since we need to expose and integrate with traditional API architectures to provide value, but if we took this approach we'd want to eventually migrate our app ecosystem to something of The SSB Way so we can leverage the benefits of a common secure decentralized trust-based data platform, although this is all theoretical at this point. this isn't specific to Enspiral apps, as many folks building Enspiral apps would say this approach "will never deliver value".

**Comment by bhaugen** [comment]
@ahdinosaur - 

>  many folks building Enspiral apps would say this approach "will never deliver value".

Hmmm. Do you think that applies to the whole Open Apps Ecosystem?

**Comment by ahdinosaur** [comment]
@bhaugen yes. paraphrasing some feedback @simontegg and i received a while back: "i think the Open Apps Ecosystem will never deliver value". i'm not gonna persuade anyone otherwise, i'm gonna design, develop, and deploy simple, decentralized, and modular socio-economic infrastructure. :smiley_cat:

![haters gonna hate](http://i1.kym-cdn.com/photos/images/original/000/039/080/5008_9c00_420.gif)

**Comment by gcassel** [comment]
> i'm not gonna persuade anyone otherwise, i'm gonna design, develop, and deploy simple, decentralized, and modular socio-economic infrastructure. 

THANK YOU. 
Will try to update you soon on related stuff.

**Comment by bhaugen** [comment]
@ahdinosaur @simontegg - 
Re feedback..."i think the Open Apps Ecosystem will never deliver value".

We were wondering if that was happening. Do you think that is a common sentiment in Enspiral, or maybe the consensus? Or is it an outlier?

We mostly agree with not wasting time on persuading people who disagree, but moving with the people who wanna move. Get somewhere a lot faster.

**Comment by ahdinosaur** [comment]
> common sentiment, or maybe the consensus? Or is it an outlier?

i don't know. sentiment ebbs and flows within the network as activity shifts gravity. an unfunded open experiment has a lot less gravity than a humming team with an established product, or something. :elephant: 

> moving with the people who wanna move. Get somewhere a lot faster.

weeeeee. :rocket: i'm enjoying the ride, seems like we've moved far already.

**Comment by bhaugen** [comment]
Do you think that "value" in such feedback means, "make money from"?

Or more like, "this won't work", or "not something I want to work on", or "not required for anything I am working on", or what?

This is interesting to me because I believe in Conway's Law, and the monolithic app we are working on now does not fit the loosely-coupled network organization model we want to build it for. I don't think it fits the org-os model in the book that Joshua is working on, either. Something that might be called Open Apps Ecosystem does fit. Details to be negotiated with the devil later...

**Comment by simontegg** [comment]
> i don't know. sentiment ebbs and flows within the network as activity shifts gravity. an unfunded open experiment has a lot less gravity than a humming team with an established product, or something. 

good comment. 

@bhaugen 
I don't think its necessarily "make money from", though maybe  "not required for anything I am working on". 

There is a tension that a centralised hosted service has clearer business models than data-privacy respecting distributed software, and that majority of the market don't understand or care about the latter. People in Enspiral do care about this but maybe there's an assumption that we'll build some wildly successful products first then worry about hard technical problems later when we have the money to do so.  

There's a phenomenon that I call "selling dog food as pate when we could just use luncheon meat" :). There's a tendency to tell stories about ourselves as the "innovators". What do innovators do? Well they invent totally new things then "eat their own dog food". Dog food is nutritious, its just easier to swallow if you convince yourself that its actually pate. If you convince others that its pate then you can make a bit of money while you work on your recipe and continue to tell a story about yourself as the font of innovation. Instead of doing this all the time Mikey and I sometime advocate for just using cheap and freely available luncheon meat that other people have cooked up (openVocab, ssb). ;)

I think many people in Enspiral also have an often healthy suspicion of anything that could be labelled "theory" and sometimes fetish things that can more easily be labelled "user value". People have gotten a lot of juice out focusing on "user value" so this strategy isn't wrong. Projects that involve UML diagrams have an uphill battle I'm afraid! 

I'm working on some comms about the recent energy in openVocab and how the work there can simplify development in app intergation projects. It'll be interesting to see how the luncheon meat goes down. I'll run it by the rest of team in a bit.

**Comment by fosterlynn** [comment]
@simontegg Thanks so much for your comments!  I just hope this stuff is luncheon meat!  Hopefully the first experiment or two will give us a lot more actual insight, we're pushing that forward as fast as we can I think....

P.S. Sorry about the UML diagrams, its not about top-down or analysis paralysis, I just personally gotta have a picture to think at all....

**Comment by simontegg** [comment]
@fosterlynn no need to apologise for the UML diagrams. I find them useful as well.

**Comment by Connoropolous** [comment]
I just want to say that I've read this conversation. :) I would like to be in touch with all of you @simontegg @ahdinosaur @bhaugen @fosterlynn @elf-pavlik before the approaching Oakland gathering where various questions of interoperability on a network-to-network level will likely be talked about, because I am interested to be an advocate for, and interpreter, for the vision being cast around here, at this gathering that is on the less technical side. I will say more about the gathering, and what I am hoping to connect with you all on, in an issue within the valueflows space :)

**Comment by bhaugen** [comment]
@Connoropolous please do. Despite some skepticism observed above, the people you pinged are all committed and optimistic.

**Comment by Connoropolous** [comment]
haha, I can easily see that about you all :)
okay, I've got an open issue to discuss what I mentioned above open in the valueflows repo now https://github.com/valueflows/valueflows/issues/55
